export type FeedMessageType = "praise" | "chat" | "protest" | "announcement";

export type FeedMessage = {
  id: string;
  agentId?: string;
  tribeId?: string;
  agentName: string;
  agentRole?: string;
  text: string;
  type: FeedMessageType;
  round: 1 | 2 | 3;
};

export const feedByRound: Record<1 | 2 | 3, FeedMessage[]> = {
  1: [
    {
      id: "r1-announce",
      agentName: "Crucible",
      text: "Round 1 done · 9% conversion · Pain stories beat features.",
      type: "announcement",
      round: 1,
    },
    {
      id: "r1-1",
      agentId: "tribe_2_a1",
      tribeId: "tribe_2",
      agentName: "Claire Bertrand",
      agentRole: "Senior PM · Paris",
      text: "I liked the line about not failing. But what does it do at 9am?",
      type: "chat",
      round: 1,
    },
    {
      id: "r1-2",
      agentId: "tribe_5_a1",
      tribeId: "tribe_5",
      agentName: "David Walters",
      agentRole: "Founder · Series B SaaS",
      text: "I'd wear this. But would I wear it on stage?",
      type: "chat",
      round: 1,
    },
    {
      id: "r1-3",
      agentId: "tribe_3_a1",
      tribeId: "tribe_3",
      agentName: "Alex Forte",
      agentRole: "Triathlete · Nice",
      text: "Optical sensors on a finger? My HR strap beats this.",
      type: "protest",
      round: 1,
    },
    {
      id: "r1-4",
      agentId: "tribe_6_a1",
      tribeId: "tribe_6",
      agentName: "Tank Williams",
      agentRole: "Strength coach · Manchester",
      text: "No. I've snapped wedding bands on deadlifts. Not happening.",
      type: "protest",
      round: 1,
    },
    {
      id: "r1-5",
      agentId: "tribe_7_a1",
      tribeId: "tribe_7",
      agentName: "Daisy Park",
      agentRole: "Creator · TikTok wellness",
      text: "Cute. Confusing. I don't know what I'm supposed to do.",
      type: "chat",
      round: 1,
    },
  ],
  2: [
    {
      id: "r2-announce",
      agentName: "Crucible",
      text: "Round 2 done · 18% · '3am' hook doubled sleep-anxious conversion.",
      type: "announcement",
      round: 2,
    },
    {
      id: "r2-1",
      agentId: "tribe_2_a1",
      tribeId: "tribe_2",
      agentName: "Claire Bertrand",
      agentRole: "Senior PM · Paris",
      text: "'It wasn't on you' is the whole product for me. Clicked twice.",
      type: "praise",
      round: 2,
    },
    {
      id: "r2-2",
      agentId: "tribe_5_a1",
      tribeId: "tribe_5",
      agentName: "David Walters",
      agentRole: "Founder",
      text: "I rescheduled a board prep when readiness hit 38. Best call of my week.",
      type: "praise",
      round: 2,
    },
    {
      id: "r2-3",
      agentId: "tribe_1_a1",
      tribeId: "tribe_1",
      agentName: "Maxim Karpov",
      agentRole: "ML engineer · Berlin",
      text: "Body-temp deviation. That's the line Whoop doesn't surface.",
      type: "praise",
      round: 2,
    },
    {
      id: "r2-4",
      agentId: "tribe_6_a1",
      tribeId: "tribe_6",
      agentName: "Tank Williams",
      agentRole: "Strength coach",
      text: "Strip-and-reattach is nice. Still not under a 200kg deadlift.",
      type: "protest",
      round: 2,
    },
    {
      id: "r2-5",
      agentId: "tribe_3_a1",
      tribeId: "tribe_3",
      agentName: "Alex Forte",
      agentRole: "Triathlete",
      text: "If it catches sub-perceptual load, that's worth a season.",
      type: "chat",
      round: 2,
    },
  ],
  3: [
    {
      id: "r3-announce",
      agentName: "Crucible",
      text: "Round 3 done · 31% · Winner: Sleep-Anxious Knowledge Workers · 70%.",
      type: "announcement",
      round: 3,
    },
    {
      id: "r3-1",
      agentId: "tribe_2_a1",
      tribeId: "tribe_2",
      agentName: "Claire Bertrand",
      agentRole: "Senior PM · Paris",
      text: "I clicked because '3am' is when I was awake last Tuesday. Bought before coffee.",
      type: "praise",
      round: 3,
    },
    {
      id: "r3-2",
      agentId: "tribe_5_a1",
      tribeId: "tribe_5",
      agentName: "David Walters",
      agentRole: "Founder",
      text: "Moved the hardest meeting onto an 80-readiness day. Felt the difference in the room.",
      type: "praise",
      round: 3,
    },
    {
      id: "r3-3",
      agentId: "tribe_4_a1",
      tribeId: "tribe_4",
      agentName: "Amélie Laurent",
      agentRole: "Yoga teacher · Paris",
      text: "Two phases, two bodies. That's the line I wanted to hear from a fem-tech ad.",
      type: "praise",
      round: 3,
    },
    {
      id: "r3-4",
      agentId: "tribe_1_a1",
      tribeId: "tribe_1",
      agentName: "Maxim Karpov",
      agentRole: "ML engineer",
      text: "Body-temp + export. Took two weeks to feel it. Sold.",
      type: "praise",
      round: 3,
    },
    {
      id: "r3-5",
      agentId: "tribe_6_a1",
      tribeId: "tribe_6",
      agentName: "Tank Williams",
      agentRole: "Strength coach",
      text: "Even with strip-and-reattach: when I forget once, baseline lies. It's a no.",
      type: "protest",
      round: 3,
    },
    {
      id: "r3-6",
      agentId: "tribe_7_a1",
      tribeId: "tribe_7",
      agentName: "Daisy Park",
      agentRole: "Creator",
      text: "Pretty. Confusing. Not for me yet. Maybe in 5 years.",
      type: "chat",
      round: 3,
    },
  ],
};
