import type { RoundResult, TribeScore } from "@/lib/types";
import { assetsRound1, assetsRound2, assetsRound3 } from "./assets";

const scoresR1: TribeScore[] = [
  {
    tribeId: "tribe_1",
    conversionRate: 0.1,
    clickRate: 0.42,
    repelledRate: 0.2,
    topPositiveWords: ["open API", "trend"],
    topObjections: ["another subscription"],
    representativeFeedback: "I clicked. But I already pay Whoop. Convince me harder.",
  },
  {
    tribeId: "tribe_2",
    conversionRate: 0.2,
    clickRate: 0.55,
    repelledRate: 0.1,
    topPositiveWords: ["no streaks", "readiness"],
    topObjections: ["apps that make me feel broken"],
    representativeFeedback: "I liked the line about not failing. But what does it actually do at 9am?",
  },
  {
    tribeId: "tribe_3",
    conversionRate: 0.0,
    clickRate: 0.28,
    repelledRate: 0.3,
    topPositiveWords: ["recovery"],
    topObjections: ["chest strap more accurate"],
    representativeFeedback: "Optical sensors on a finger? My HR strap will beat this all day.",
  },
  {
    tribeId: "tribe_4",
    conversionRate: 0.1,
    clickRate: 0.48,
    repelledRate: 0.2,
    topPositiveWords: ["privacy", "phase"],
    topObjections: ["app companies don't keep their privacy promises"],
    representativeFeedback: "Privacy was the only line that made me read on. Show me the policy.",
  },
  {
    tribeId: "tribe_5",
    conversionRate: 0.2,
    clickRate: 0.58,
    repelledRate: 0.1,
    topPositiveWords: ["discreet", "peak"],
    topObjections: ["visible on hand"],
    representativeFeedback: "I'd wear this. But would I wear it on stage?",
  },
  {
    tribeId: "tribe_6",
    conversionRate: 0.0,
    clickRate: 0.15,
    repelledRate: 0.5,
    topPositiveWords: [],
    topObjections: ["ring under a barbell"],
    representativeFeedback: "No. I've snapped wedding bands on deadlifts. Not happening.",
  },
  {
    tribeId: "tribe_7",
    conversionRate: 0.0,
    clickRate: 0.2,
    repelledRate: 0.4,
    topPositiveWords: ["beautiful"],
    topObjections: ["too much data"],
    representativeFeedback: "Cute. Confusing. I don't know what I'm supposed to do with it.",
  },
];

const scoresR2: TribeScore[] = [
  {
    tribeId: "tribe_1",
    conversionRate: 0.2,
    clickRate: 0.6,
    repelledRate: 0.05,
    topPositiveWords: ["body-temp", "compare"],
    topObjections: ["I already own Whoop"],
    representativeFeedback: "Body-temp deviation is the line. Whoop doesn't surface it like that.",
  },
  {
    tribeId: "tribe_2",
    conversionRate: 0.4,
    clickRate: 0.78,
    repelledRate: 0.05,
    topPositiveWords: ["3am", "reason", "no shame"],
    topObjections: ["one more thing on my phone"],
    representativeFeedback: "'It wasn't on you' is the whole product for me. That's why I clicked twice.",
  },
  {
    tribeId: "tribe_3",
    conversionRate: 0.1,
    clickRate: 0.45,
    repelledRate: 0.2,
    topPositiveWords: ["coach can't see"],
    topObjections: ["accuracy under tempo"],
    representativeFeedback: "If it really catches sub-perceptual load, that's worth a season.",
  },
  {
    tribeId: "tribe_4",
    conversionRate: 0.2,
    clickRate: 0.55,
    repelledRate: 0.1,
    topPositiveWords: ["phase plan", "private"],
    topObjections: ["second cycle to trust it"],
    representativeFeedback: "I'd give it two cycles. Local-only is the right call.",
  },
  {
    tribeId: "tribe_5",
    conversionRate: 0.4,
    clickRate: 0.75,
    repelledRate: 0.05,
    topPositiveWords: ["readiness 32", "boardroom"],
    topObjections: ["streak shame"],
    representativeFeedback: "I rescheduled a board prep when readiness hit 38. Best call of my week.",
  },
  {
    tribeId: "tribe_6",
    conversionRate: 0.0,
    clickRate: 0.22,
    repelledRate: 0.4,
    topPositiveWords: ["strip and reattach"],
    topObjections: ["still going to break under a bar"],
    representativeFeedback: "I appreciate the workaround. I'm still not putting it under a 200kg deadlift.",
  },
  {
    tribeId: "tribe_7",
    conversionRate: 0.0,
    clickRate: 0.3,
    repelledRate: 0.3,
    topPositiveWords: ["one number"],
    topObjections: ["I still don't know what I'm supposed to do"],
    representativeFeedback: "Less data is good. But what's my action?",
  },
];

const scoresR3: TribeScore[] = [
  {
    tribeId: "tribe_1",
    conversionRate: 0.4,
    clickRate: 0.7,
    repelledRate: 0.0,
    topPositiveWords: ["temperature", "export"],
    topObjections: ["price"],
    representativeFeedback: "Body-temp + export is the combo. Took two weeks to feel it.",
  },
  {
    tribeId: "tribe_2",
    conversionRate: 0.7,
    clickRate: 0.92,
    repelledRate: 0.0,
    topPositiveWords: ["3am", "reason", "no blame"],
    topObjections: ["another wearable"],
    representativeFeedback:
      "I clicked because '3am' is when I was awake last Tuesday. I'd never seen that turned into evidence.",
  },
  {
    tribeId: "tribe_3",
    conversionRate: 0.2,
    clickRate: 0.62,
    repelledRate: 0.1,
    topPositiveWords: ["felt easy but wasn't"],
    topObjections: ["want chest-strap parity"],
    representativeFeedback: "Once it caught the day my coach missed, I was sold for a season.",
  },
  {
    tribeId: "tribe_4",
    conversionRate: 0.3,
    clickRate: 0.68,
    repelledRate: 0.0,
    topPositiveWords: ["two phases, two bodies"],
    topObjections: ["wait for second cycle"],
    representativeFeedback: "Two phases, two bodies — that's the line I wanted to hear from a fem-tech ad.",
  },
  {
    tribeId: "tribe_5",
    conversionRate: 0.6,
    clickRate: 0.85,
    repelledRate: 0.0,
    topPositiveWords: ["peak day", "boardroom"],
    topObjections: ["streaks"],
    representativeFeedback:
      "I moved my hardest meeting onto an 80-readiness day. I felt the difference in the room.",
  },
  {
    tribeId: "tribe_6",
    conversionRate: 0.0,
    clickRate: 0.18,
    repelledRate: 0.5,
    topPositiveWords: [],
    topObjections: ["physical objection unresolved"],
    representativeFeedback: "Even with strip-and-reattach: when I forget once, baseline lies. It's a no.",
  },
  {
    tribeId: "tribe_7",
    conversionRate: 0.0,
    clickRate: 0.32,
    repelledRate: 0.3,
    topPositiveWords: ["one sentence"],
    topObjections: ["price for a vibe check"],
    representativeFeedback: "Pretty. Confusing. Not for me yet. Maybe in 5 years.",
  },
];

export const roundResults: RoundResult[] = [
  {
    round: 1,
    overallConversion: 0.09,
    learning:
      "Broad messaging underperforms. The two audiences with chronic, named pain — sleep-anxious workers and recovering execs — led on conversion. Athletes were skeptical of optical-sensor accuracy. The strength tribe was repelled by the physical 'ring under a barbell' objection.",
    highlights: [
      "Sleep-anxious + execs lead — pain stories beat features",
      "Cycle privacy line lands for women who lost trust in 2022",
      "Biohackers click but don't convert without proof",
    ],
    failures: [
      "Strength tribe: ring + barbell objection blocks all messages",
      "Wellness beginners: overwhelmed by data, no clear action",
      "Endurance: 'chest strap is more accurate' kills conversion",
    ],
    assets: assetsRound1,
    tribeScores: scoresR1,
  },
  {
    round: 2,
    overallConversion: 0.18,
    learning:
      "Hooks sharpened around chronic pain + a believable trigger ('3am', 'meeting at readiness 32'). Conversion doubled on the two leading tribes. Athletes opened up to a coach-comparison framing. The strength tribe is still physically blocked.",
    highlights: [
      "'It wasn't on you' converts sleep-anxious workers 2x",
      "'Lead at 32' lands for execs who already had a bad meeting",
      "Body-temp deviation unlocked biohacker conversion",
    ],
    failures: [
      "Strength: physical objection remains structural",
      "Wellness: less data is good, but they still need an action",
      "Endurance: improved but accuracy doubt persists",
    ],
    assets: assetsRound2,
    tribeScores: scoresR2,
  },
  {
    round: 3,
    overallConversion: 0.31,
    learning:
      "Sleep-anxious workers and execs converged on one shared pain: 'A bad day with no reason.' The winning hook names the moment + promises a 30-second answer. Conversion 31%, with 7/10 of the sleep-anxious tribe converting.",
    highlights: [
      "Winning hook: 'Your worst night had a reason. Look it up tomorrow.'",
      "Sleep-anxious tribe converts at 70% — clear winner",
      "Execs second at 60% — share the same hook, different platform",
    ],
    failures: [
      "Strength: do not target — physical objection is structural",
      "Wellness beginners: this is a different product position",
    ],
    assets: assetsRound3,
    tribeScores: scoresR3,
  },
];
